spring:
  application:
        name: WeatherApi


ipapi:
   api: http://api.ipapi.com
   key: de2597fd686079938693ec647464bbe9
weather:
    api: https://weather-api167.p.rapidapi.com/api/weather
    key: 0c656e7a1emsh95120070af84edbp127857jsn34f2e3bd6fcb
